// This file is generated by Terraform
// Environment-specific configuration

const CONFIG = {
    environment: "${environment}",
    difficulty: "${difficulty}",
    startingResources: {
        wood: ${starting_wood},
        stone: ${starting_stone},
        food: ${starting_food}
    },
    gameSettings: {
        hungerDecayRate: ${hunger_decay},
        thirstDecayRate: ${thirst_decay},
        energyDecayRate: ${energy_decay},
        resourceMultiplier: ${resource_multiplier},
        dangerLevel: ${danger_level}
    },
    features: {
        craftingEnabled: ${crafting_enabled},
        weatherEvents: ${weather_events},
        randomEvents: ${random_events}
    },
    deploymentInfo: {
        version: "${version}",
        deployedBy: "terraform",
        timestamp: new Date().toISOString()
    }
};

// Export for use in game
window.GAME_CONFIG = CONFIG;
