// This file is generated by Terraform
// Environment-specific configuration

const CONFIG = {
    environment: "development",
    difficulty: "normal",
    startingResources: {
        wood: 5,
        stone: 3,
        food: 2
    },
    gameSettings: {
        hungerDecayRate: 2,
        thirstDecayRate: 3,
        energyDecayRate: 1.5,
        resourceMultiplier: 1.0,
        dangerLevel: 0.3
    },
    features: {
        craftingEnabled: true,
        weatherEvents: true,
        randomEvents: true
    },
    deploymentInfo: {
        version: "1.0.0",
        deployedBy: "terraform",
        timestamp: new Date().toISOString()
    }
};

// Export for use in game
window.GAME_CONFIG = CONFIG;
